### ISSUE TITLE
Missing cfg files

### ISSUE THREAD

**Issue by thezeagar** [thebezelproject/bezelproject-SNES#1]
I've noticed while setting up SNES that many .png bezel files don't have a .cfg to go with them, causing the Bezel to not work.

This mostly effects games with revisions. Use Mega Man X as an example. There's a bezel file for Mega Man X (USA) (Rev 1).png but there is no corresponding .cfg, so the bezel doesn't load if you have a properly named Rev 1 rom..

I've checked many of my roms that have revisions and this seems to be the case for all of them. The bezel project has a .png for them, but no .cfg.

I have come across a few games missing .cfg files that aren't revisions. There's a bezel .png for Star Fox 2, but it's missing the cfg. Same problem with New Horizons (USA).png

**Comment by thebezelproject** [comment]
Created missing cfg files.
