### ISSUE TITLE
Bezel uses art from the “wrong” Final Fantasy III

### ISSUE THREAD

**Issue by MWDelaney** [thebezelproject/bezelproject-SNES#2]
Hi,
The artwork for the SNES Final Fantasy III bezel (https://github.com/thebezelproject/bezelproject-SNES/blob/master/retroarch/overlay/GameBezels/SNES/Final%20Fantasy%20III%20(USA).png) uses imagery from the Japanese FF3, which was a different game. The US FF3 was actually the Japanese FF6, so the artwork should be either from FF6(jp) or from the US release and marketing of FF3(us).

**Comment by thebezelproject** [comment]
It's been fixed
