### ISSUE TITLE
Overlays contain transparent / translucent pixels outside the desired area

### ISSUE THREAD

**Issue by toniosj** [thebezelproject/bezelproject-SNES#4]
Some overlays contain transparent / translucent pixels outside the desired area.
![Castlevania - Dracula X (USA)](https://user-images.githubusercontent.com/20826760/74614025-6aba2000-5114-11ea-8098-f2646d28fa25.png)

Here the list:

Carrier Aces (USA).png
Castlevania - Dracula X (USA).png
Chester Cheetah - Too Cool to Fool (USA).png
Pinocchio (USA).png
Plok (USA).png
Pocky & Rocky (USA).png
Pocky & Rocky 2 (USA).png
Porky Pig's Haunted Holiday (USA).png
Prince of Persia (USA).png
Scooby-Doo Mystery (USA).png
Soldiers of Fortune (USA).png
Sonic Blast Man (USA).png
Soul Blazer (USA).png
Spanky's Quest (USA).png
Sparkster (USA).png
Spider-Man - Venom - Maximum Carnage (USA).png
Spider-Man - X-Men - Arcade's Revenge (USA).png
Super Conflict (USA).png
Super Godzilla (USA).png
Super Mario All-Stars + Super Mario World (USA).png
Super Mario RPG - Legend of the Seven Stars (USA).png
Super Ninja Boy (USA).png
Super Putty (USA).png
Super Shadow of the Beast (USA) (Proto).png
Super Slap Shot (USA).png

Here you can see the specific areas that have pixels outside the desired area.

https://drive.google.com/file/d/1fGNYPXMcfU_xX8ONo3OLlgrYifjw-GCe/view?usp=sharing

**Comment by thebezelproject** [comment]
Thanks! I have updated these.
