### ISSUE TITLE
Missing Boxart 3D

### ISSUE THREAD

**Issue by toniosj** [thebezelproject/bezelproject-SNES#5]
I have seen that some overlays that do not have the BOXART3D image in the lower right. I can send you all the BOXART to add them and follow the design pattern.

**Comment by thebezelproject** [comment]
Using the boxart was a design decision made by a certain artist. The base template does not include, or require boxart to be used. We have a totally volunteer group who chips in to make these bezels. Each artist is free to create whatever design they want. There is no plan to go back and rework each bezel to include boxart. Feel free to create and modify our design to customize your own.
