### ISSUE TITLE
Overlays contain transparent / translucent pixels outside the desired area

### ISSUE THREAD

**Issue by toniosj** [thebezelproject/bezelproject-SNES#7]
Beavis and Butt-Head (USA).png
Bill Walsh College Football (USA).png
Brawl Brothers (USA).png
Captain Commando (USA).png
Fatal Fury (USA).png
Final Fantasy - Mystic Quest (USA).png

![Beavis and Butt-Head (USA)_bezel-16-9(us) - 1_yellow](https://user-images.githubusercontent.com/20826760/101485018-d519a680-395a-11eb-9010-67a12e468696.png)
![Bill Walsh College Football (USA)_bezel-16-9(us) - 1_yellow](https://user-images.githubusercontent.com/20826760/101485022-d64ad380-395a-11eb-817d-3e1e5188a412.png)
![Brawl Brothers (USA)_bezel-16-9(us) - 1_yellow](https://user-images.githubusercontent.com/20826760/101485023-d64ad380-395a-11eb-83bb-3866c5444b82.png)
![Captain Commando (USA)_bezel-16-9(us) - 1_yellow](https://user-images.githubusercontent.com/20826760/101485027-d77c0080-395a-11eb-8db1-fc42c050bc75.png)
![Fatal Fury (USA)_bezel-16-9(us) - 1_yellow](https://user-images.githubusercontent.com/20826760/101485030-d8149700-395a-11eb-8b5e-d7df39d3d707.png)
![Final Fantasy - Mystic Quest (USA) (Rev 1)_bezel-16-9(us) - 1_yellow](https://user-images.githubusercontent.com/20826760/101485033-d8149700-395a-11eb-84ff-847b6dd51bff.png)

**Comment by thebezelproject** [comment]
Updated.
