### ISSUE TITLE
Super Mario World - pixilated and artifacts

### ISSUE THREAD

**Issue by Zenjir0** [thebezelproject/bezelproject-SNES#8]
The Super Mario World Bezel has many artifacts and appears pixelated:

Click image to view in full screen to better see what I am talking about.

![Super Mario World (USA)](https://user-images.githubusercontent.com/27794756/119752261-33483080-be8c-11eb-8c72-1e9236e2310a.png)

**Comment by thebezelproject** [comment]
The bezels are created by different volunteers with different access the the best art. Having said that, I'll add this one to the work queue to see how it can be reworked. Thanks!

**Comment by thebezelproject** [comment]
File updated.
