### ISSUE TITLE
Upper case on file name doesn't work in Linux

### ISSUE THREAD

**Issue by spilinek** [thebezelproject/bezelproject-SNES#9]
Issues in retroarch/overlay/GameBezels/SNES/ using the wrong case.

Featuring: 

- Newman-Haas IndyCar Featuring Nigel Mansell (USA).png

Should be featuring: 

- Newman-Haas IndyCar **featuring** Nigel Mansell (USA).png

SkulJagger: 

- SkulJagger - Revolt of the Westicans (USA).png

Should be Skuljagger:
- Skuljagger - Revolt of the Westicans (USA).png

**Comment by thebezelproject** [comment]
Many thanks for reporting this item. The files have been renamed.
